### ISSUE TITLE
Responsive Image solution survey

### ISSUE THREAD

**Issue by devformatters** [thematters/serverless-file-post-processing#638]
### Tasks

- [x] ~~Confirm the correct setting value with designer~~
  - me avatar
  - user profile background
  - user profile avatar
  - collection article thumbnail
  - recommendation article thumbnail
- [x] Figure out a frontend solution
- [x] Figure out a migration solution

### References

- [Thread discussion #1](https://mattersnews.slack.com/archives/GA0R09FHN/p1668069509337389?thread_ts=1668065406.589319&cid=GA0R09FHN)
- [Thread discussion #2](https://mattersnews.slack.com/archives/GA0R09FHN/p1668435162171879?thread_ts=1668065406.589319&cid=GA0R09FHN)

**Comment by robertu7** [comment]
### Migration (8-13pts)
- Count the total number of (original) images to be migrated and estimate costs;
- Migrate all original images from AWS S3 to Cloudflare images in one of the following ways:
  - [Sourcing Kit](https://developers.cloudflare.com/images/cloudflare-images/sourcing-kit/) [2]
  - [Upload via URL](https://developers.cloudflare.com/images/cloudflare-images/upload-images/upload-via-url/) with [Custom ID](https://developers.cloudflare.com/images/cloudflare-images/upload-images/custom-id/) [0]
- Check if different formats of images (JPEG, JPG, PNG, GIF, SVG, etc.) are able to access with [variants](https://developers.cloudflare.com/images/cloudflare-images/transform/flexible-variants/);
- ~~Replace image URLs of `draft.content` and `article.content` with new images URLs~~

### Server-side changes (~8pts)
- For images, revise API to upload them to **both** AWS S3 and Cloudflare Images [0] for backward compatibility;
  - `singleFileUpload` mutation;
  - `updateUserInfo` mutation;
  - `routes/img-cache`;
  - Migration from Medium.com;
  -  CURD methods on `systemService`;
- For other formats of files, keep uploading to AWS S3;
- Possible changes on `asset` table; 

### Client-side changes (~5pts)
- Revise `<ResponsiveImage>` component to support [variants](https://developers.cloudflare.com/images/cloudflare-images/transform/flexible-variants/);
- Revise `optimizeEmbed` util: `asset.matters.news` -> Cloudflare Images URL;
- Revise CSP;

### Release Steps
- Deploy server-side changes: w/o returning URL of Cloudflare Images [1];
- Migration;
- Deploy server-side: with returning URL of Cloudflare Images;
- Deploy client-side changes;

### Todo
* Support more formats: WebP, SVG;
* Increase size limits;
* Stop uploading images to AWS S3;
* More flexible variants on different components;

### References
* Est. Costs: https://www.notion.so/matterslab/Storage-Usage-c011fa6b01d848b49dd2709ffc324b8b

[0] Use [Custom ID](https://developers.cloudflare.com/images/cloudflare-images/upload-images/custom-id/) to keep the URL path (contains UUID recorded in database) same as S3;
[1] Start storing images in both AWS S3 and Cloudflare Images;
[2] Image ID will be `BUCKET_FOLDER_NAME/FILENAME.EXT`;
